<?php

/**
 * @file
 * The Cirro AJAX framework, which controlls AJAX communication on the site.
 */

/**
 * Implements hook_menu()
 */
function cirro_ajax_menu() {

	// The Cirro AJAX framework
	$items['cirro/ajax'] = array(
		'page callback' => 'cirro_ajax_framework',
		'access arguments' => array('access content'),
		'file' => 'cirro_ajax_framework.inc',
	);

	return $items;

}

/**
 * Implements hook_init()
 */
function cirro_ajax_init() {

	// Init
	global $theme;
	$module_path = drupal_get_path('module', 'cirro_ajax');
	$js_path = '';

	// If not the clim admin theme
	if ( $theme !== 'climAdmin' ) {

		// Add the Cirro.ajax.js script to all pages for AJAX framework access
		$js_path = $module_path . '/js/Cirro.ajax.js';
		drupal_add_js($js_path, array('weight' => 20));

	}

}