<?php
/**
	* @file
	* 	Blog page load
	*/

/**
	*	Implements hook_menu()
	*/
function landl_blog_menu(){

	$items = array();
	
	// Contact Page
	$items['blog'] = array(
		'title' => t('Blog'),
		'page callback' => 'landl_blog_general_overview',
		'access arguments' => array('access content'),
		'file' => 'landl_blog_general_overview.inc',
		'type' => MENU_CALLBACK,
	);
	
	$items['blog/%'] = array(
		'title' => t('Blog'),
		'page callback' => 'landl_blog_overview',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'file' => 'landl_blog_overview.inc',
		'type' => MENU_CALLBACK,
	);

	$items['blog/%/%cirro_core_single'] = array(
		'load arguments' => array('blog'),
		'page callback' => 'landl_blog_individual_display',
		'page arguments' => array(1, 2),
		'access arguments' => array('access content'),
		'file' => 'individual_display.inc',
		'type' => MENU_CALLBACK,
	);
	
	
	return $items;
	
}

/**
	*	Implements hook_init()
	*/

function landl_blog_init(){
	
	// Make include function names globally available to blog section
	module_load_include('inc', 'landl_blog', 'landl_blog_general_overview');
	module_load_include('inc', 'landl_blog', 'landl_blog_overview');
	
}


























































